name: Upload Go test results

on: [push]

jobs:
  build:

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
          
      - name: Install dependencies
        run: go get .
    
      - name: Test with Go
        run: go test -json > TestResults-${{ matrix.os }}.json
    
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-results-${{ matrix.os }}
          path: TestResults-${{ matrix.os }}.json
    
      - name: Build
        run: go build .

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact-${{ matrix.os }}
          path: go-sha256
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set Tag Date
        id: tag
        run: echo "TAG_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
      
      - name: Download build artifacts for Windows
        uses: actions/download-artifact@v4
        with:
          name: build-artifact-windows-latest.exe
          path: build-windows

      - name: Download build artifacts for Linux
        uses: actions/download-artifact@v4
        with:
          name: build-artifact-ubuntu-latest
          path: build-linux

      - name: Download build artifacts for macOS
        uses: actions/download-artifact@v4
        with:
          name: build-artifact-macos-latest
          path: build-macos

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_DATE }}
          name: Release ${{ env.TAG_DATE }}
          files: |
            build-windows/go-sha256-windows.exe
            build-linux/go-sha256-linux
            build-macos/go-sha256-macos
